import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/layouts/Layout.module.scss";
import type { ReactNode } from "react";
import Navigation from "./Navigation";

type Props = {
  children: ReactNode;
  title: string;
};

export default function Layout({ children, title }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <div className={styles.container}>{children}</div>
    </>
  );
}
