import React from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "./Layout.module.scss";
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
  title: string;
};

export default function Layout({ children, title }: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <header className={styles.header}>
          <img src="" alt="" />
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/posts">Posts</Link>
            </li>
            <li>
              <Link href="posts/create">Create</Link>
            </li>
            <li>
              <Link href="/mypage">Mypage</Link>
            </li>
            <li>
              <Link href="/signin">Signin</Link>
            </li>
          </ul>
        </header>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>
          <span>sharefolio 2022</span>
        </footer>
      </div>
    </>
  );
}
